In [8]:
import numpy as np
import matplotlib.pyplot as plt
import keras

In [9]:
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

In [10]:
x_train = x_train.reshape(-1, 28*28) / 255
x_test = x_test.reshape(-1, 28*28) / 255
print(x_train.shape)
print(x_test.shape)

(60000, 784)
(10000, 784)


In [21]:
w1 = np.random.randn(28*28, 128) * 0.01
b1 = np.zeros((1, 128))
w2 = np.random.randn(128, 10) * 0.01
b2 = np.zeros((1, 10))

In [22]:
x = x_train[:10]
label = y_train[:10]
print(x.shape)
print(label)

(10, 784)
[5 0 4 1 9 2 1 3 1 4]


In [23]:
y = np.zeros((10, 10))
y[np.arange(10), label] = 1

In [24]:
print(y)

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [27]:
for epoch in range(1000):
    # Forward pass
    z1 = np.dot(x, w1) + b1
    a1 = np.maximum(0, z1) # ReLU activation
    z2 = np.dot(a1, w2) + b2
    exp = np.exp(z2 - np.max(z2, axis=1, keepdims=True))
    softmax = exp / np.sum(exp, axis=1, keepdims=True)

    # Loss
    correct_prob = softmax[np.arange(10), label]
    loss = -np.mean(np.log(correct_prob))

    # Bakward pass
    dz2 = softmax - y

    dw2 = np.dot(a1.T, dz2)
    db2 = np.sum(dz2, axis=0, keepdims=True)

    da1 = np.dot(dz2, w2.T)
    dz1 = da1 * (z1 > 0) #Derivative of ReLU

    dw1 = np.dot(x.T, dz1)
    db1 = np.sum(dz1, axis=0, keepdims=True)

    learning_rate = 0.1

    w1 -= learning_rate * dw1
    b1 -= learning_rate * db1

    w2 -= learning_rate * dw2
    b2 -= learning_rate * db2

    if epoch % 100 == 0:
        predicted_class = np.argmax(softmax, axis=1)
        confidence = np.max(softmax, axis=1)
        print(f"Epoch {epoch}: Loss = {loss:.4f}, Predicted class = {predicted_class}, Confidence = {confidence}")


Epoch 0: Loss = 2.1654, Predicted class = [1 1 1 1 1 1 1 1 1 1], Confidence = [0.12921001 0.12504625 0.12398263 0.12995815 0.13028664 0.12925058
 0.13424166 0.12963856 0.13088872 0.12857166]
Epoch 100: Loss = 0.0006, Predicted class = [5 0 4 1 9 2 1 3 1 4], Confidence = [0.99914826 0.99946557 0.99967396 0.99939826 0.99940035 0.99923985
 0.99990948 0.99881952 0.99932386 0.99958781]
Epoch 200: Loss = 0.0003, Predicted class = [5 0 4 1 9 2 1 3 1 4], Confidence = [0.99964031 0.99975587 0.99984574 0.99973979 0.99971827 0.9996513
 0.99996316 0.99950223 0.99967943 0.99982101]
Epoch 300: Loss = 0.0002, Predicted class = [5 0 4 1 9 2 1 3 1 4], Confidence = [0.99977757 0.99984429 0.99989951 0.99983828 0.99981644 0.99977793
 0.99997791 0.99969364 0.99979115 0.99988822]
Epoch 400: Loss = 0.0001, Predicted class = [5 0 4 1 9 2 1 3 1 4], Confidence = [0.99984069 0.9998867  0.99992571 0.99988406 0.99986489 0.99983834
 0.99998461 0.99978154 0.99984584 0.99991966]
Epoch 500: Loss = 0.0001, Predicted cl

In [31]:
# Forward pass
z1 = np.dot(x, w1) + b1
a1 = np.maximum(0, z1)  # ReLU activation
z2 = np.dot(a1, w2) + b2
exp = np.exp(z2)
softmax = exp / np.sum(exp, axis=1, keepdims=True)

predictions = np.argmax(softmax, axis=1)
confidence = np.max(softmax, axis=1)

print(f"Final Prediction: {prediction}, Confidence: {confidence}")

Final Prediction: 61, Confidence: [0.99994687 0.99995881 0.99997155 0.99995903 0.99994951 0.99994103
 0.99999509 0.99992446 0.99994136 0.99997162]
